project:
  type: website

website:
  title: "Saturnalia guide"
  navbar:
    pinned: true
    left:
      - href: clues.qmd
        text: Clues
      - town_quest.qmd
      - href: anita.qmd
        text: Anita

format:
  html:
    theme: [cosmo, borderless.scss]
    css: styles.css
    toc: true

execute:
  freeze: auto