project:
  type: website
  resources: [images, www]

website:
  title: "Saturnalia guide"
  navbar:
    pinned: true
    left:
      - href: clues.qmd
        text: Clues
      - contribute.qmd
      # - town_quest.qmd
      # - href: anita.qmd
      #   text: Anita

format:
  html:
    theme: [cosmo, borderless.scss]
    css: styles.css
    toc: true

execute:
  freeze: auto